<?php
declare(strict_types=1);
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search articles
    </h1>
    <p>
        <?php echo $this->tag::linkTo(['admin/articles/new', 'Create articles']) ?>
    </p>
    <p>
        <?php echo $this->tag::linkTo(['admin/articles/list', 'List']) ?>
    </p>
    <p>
        <?= $this->tag::linkTo(['admin', 'Main ']); ?>
    </p>
</div>

<?php if (isset($_GET['notice'])) : ?>
    <div style="text-align: center;color:coral;"><?php echo urldecode($_GET['notice']); ?></div>
<?php endif; ?>
<?php if (isset($_GET['success'])) : ?>
    <div style="text-align: center;color:darkolivegreen;"><?php echo urldecode($_GET['success']); ?></div>
<?php endif; ?>
<?php echo $this->getContent() ?>

<?php
echo $this->tag::form(
    [
        'admin/articles/search',
        'autocomplete' => 'off',
        'class' => 'form-horizontal'
    ]
);
?>

<div class="form-group">
    <label for="fieldId" class="col-sm-2 control-label">Id</label>
    <div class="col-sm-10">
        <?php echo $this->tag::textField(['id', 'type' => 'number', 'class' => 'form-control', 'id' => 'fieldId']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldTitle" class="col-sm-2 control-label">Title</label>
    <div class="col-sm-10">
        <?php echo $this->tag::textField(['title', 'size' => 30, 'class' => 'form-control', 'id' => 'fieldTitle']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDescription" class="col-sm-2 control-label">Description</label>
    <div class="col-sm-10">
        <?php echo $this->tag::textArea(['description', 'cols' => 30, 'rows' => 4, 'class' => 'form-control', 'id' => 'fieldDescription']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldText" class="col-sm-2 control-label">Text</label>
    <div class="col-sm-10">
        <?php echo $this->tag::textArea(['text', 'cols' => 30, 'rows' => 4, 'class' => 'form-control', 'id' => 'fieldText']) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag::submitButton(['Search', 'class' => 'btn btn-info']) ?>
    </div>
</div>

<?php echo $this->tag::endForm(); ?>
